consonants = {
    'b': {'desc': 'voiced bilabial plosive', 'uni': '\u0062'},
    'b_<': {'desc': 'voiced bilabial implosive', 'uni': '\u0253'},
    'c': {'desc': 'voiceless palatal plosive', 'uni': '\u0063'},
    'd': {'desc': 'voiced alveolar plosive', 'uni': '\u0064'},
    'd`': {'desc': 'voiced retroflex plosive', 'uni': '\u0256'},
    'd_<': {'desc': 'voiced alveolar implosive', 'uni': '\u0257'},
    'f': {'desc': 'voiceless labiodental fricative', 'uni': '\u0066'},
    'g': {'desc': 'voiced velar plosive', 'uni': '\u0261'},
    'g_<': {'desc': 'voiced velar implosive', 'uni': '\u0260'},
    'h': {'desc': 'voiceless glottal fricative', 'uni': '\u0068'},
    'h*': {'desc': 'voiced glottal fricative', 'uni': '\u0266'},
    'j': {'desc': 'palatal approximant', 'uni': '\u006a'},
    'j*': {'desc': 'voiced palatal fricative', 'uni': '\u029d'},
    'k': {'desc': 'voiceless velar plosive', 'uni': '\u006b'},
    'l': {'desc': 'alveolar lateral approximant', 'uni': '\u006c'},
    'l`': {'desc': 'retroflex lateral approximant', 'uni': '\u026d'},
    'l*': {'desc': 'alveolar lateral flap', 'uni': '\u027a'},
    'm': {'desc': 'voiced bilabial nasal', 'uni': '\u006d'},
    'n': {'desc': 'voiced alveolar nasal', 'uni': '\u006e'},
    'n`': {'desc': 'voiced retroflex nasal', 'uni': '\u0273'},
    'p': {'desc': 'voiceless bilabial plosive', 'uni': '\u0070'},
    'p*': {'desc': 'voiceless bilabial fricative', 'uni': '\u0278'},
    'q': {'desc': 'voiceless uvular plosive', 'uni': '\u0071'},
    'r': {'desc': 'voiced alveolar trill', 'uni': '\u0072'},
    'r`': {'desc': 'voiced retroflex flap', 'uni': '\u027d'},
    'r*': {'desc': 'voiced alveolar approximant', 'uni': '\u0279'},
    'r*`': {'desc': 'voiced retroflex approximant', 'uni': '\u027b'},
    's': {'desc': 'voiceless alveolar fricative', 'uni': '\u0073'},
    's`': {'desc': 'voiceless retroflex fricative', 'uni': '\u0282'},
    's*': {'desc': 'voiceless alveolo-palatal fricative', 'uni': '\u0255'},
    't': {'desc': 'voiceless alveolar plosive', 'uni': '\u0074'},
    't`': {'desc': 'voiceless retroflex plosive', 'uni': '\u0288'},
    'v': {'desc': 'voiced labiodental fricative', 'uni': '\u0076'},
    'v*': {'desc': 'labiodental approximant', 'uni': '\u028b'},
    'w': {'desc': 'voiced labial-velar approximant', 'uni': '\u0077'},
    'x': {'desc': 'voiceless velar fricative', 'uni': '\u0078'},
    'x*': {'desc': 'voiceless palatal-velar fricative', 'uni': '\u0267'},
    'z': {'desc': 'voiced alveolar fricative', 'uni': '\u007a'},
    'z`': {'desc': 'voiced retroflex fricative', 'uni': '\u0290'},
    'z*': {'desc': 'voiced alveolo-palatal fricative', 'uni': '\u0291'},
    'B': {'desc': 'voiced bilabial fricative', 'uni': '\u03b2'},
    'B*': {'desc': 'voiced bilabial trill', 'uni': '\u0299'},
    'C': {'desc': 'voiceless palatal fricative', 'uni': '\u00e7'},
    'D': {'desc': 'voiced dental fricative', 'uni': '\u00f0'},
    'F': {'desc': 'voiced labiodental nasal', 'uni': '\u0271'},
    'G': {'desc': 'voiced velar fricative', 'uni': '\u0263'},
    'G*': {'desc': 'voiced uvular plosive', 'uni': '\u0262'},
    'G*_<': {'desc': 'voiced uvular implosive', 'uni': '\u029b'},
    'H': {'desc': 'voiced labial-palatal approximant', 'uni': '\u0265'},
    'H*': {'desc': 'voiceless epiglottal fricative', 'uni': '\u029c'},
    'J': {'desc': 'voiced palatal nasal', 'uni': '\u0272'},
    'J*': {'desc': 'voiced palatal plosive', 'uni': '\u025f'},
    'J*_<': {'desc': 'voiced palatal implosive', 'uni': '\u0284'},
    'K': {'desc': 'voiceless alveolar lateral fricative', 'uni': '\u026c'},
    'K*': {'desc': 'voiced alveolar lateral fricative', 'uni': '\u026e'},
    'L': {'desc': 'voiced palatal lateral approximant', 'uni': '\u028e'},
    'L*': {'desc': 'voiced velar lateral approximant', 'uni': '\u029f'},
    'M*': {'desc': 'voiced velar approximant', 'uni': '\u0270'},
    'N': {'desc': 'voiced velar nasal', 'uni': '\u014b'},
    'N*': {'desc': 'voiced uvular nasal', 'uni': '\u0274'},
    'O*': {'desc': 'bilabial click', 'uni': '\u0298'},
    'R': {'desc': 'voiced uvular fricative', 'uni': '\u0281'},
    'R*': {'desc': 'voiced uvular trill', 'uni': '\u0280'},
    'S': {'desc': 'voiceless postalveolar fricative', 'uni': '\u0283'},
    'T': {'desc': 'voiceless dental fricative', 'uni': '\u03b8'},
    'W': {'desc': 'voiceless labial-velar fricative', 'uni': '\u028d'},
    'X': {'desc': 'voiceless uvular fricative', 'uni': '\u03c7'},
    'X*': {'desc': 'voiceless pharyngeal fricative', 'uni': '\u0127'},
    'Z': {'desc': 'voiced postalveolar fricative',  'uni': '\u0292'},
    '4': {'desc': 'voiced alveolar tap', 'uni': '\u027e'},
    '?': {'desc': 'glottal stop', 'uni': '\u0294'},
    '?*': {'desc': 'voiced pharyngeal fricative', 'uni': '\u0295'},
    '<*': {'desc': 'voiced epiglottal trill', 'uni': '\u02a2'},
    '>*': {'desc': 'epiglottal plosive', 'uni': '\u02a1'}
}
# need to add clicks and DARK L

vowels = {
    'a': {'desc': 'open front unrounded vowel', 'uni': '\u0061'},
    'e': {'desc': 'close-mid front unrounded vowel', 'uni': '\u0065'},
    'i': {'desc': 'close front unrounded vowel', 'uni': '\u0069'},
    'o': {'desc': 'close-mid back rounded vowel', 'uni': '\u006f'},
    'u': {'desc': 'close back rounded vowel', 'uni': '\u0075'},
    'y': {'desc': 'close front rounded vowel', 'uni': '\u0079'},
    'A': {'desc': 'open back unrounded vowel', 'uni': '\u0251'},
    'E': {'desc': 'open-mid front unrounded vowel', 'uni': '\u025b'},
    'I': {'desc': 'near-close front unrounded vowel', 'uni': '\u026a'},
    '1': {'desc': 'close central unrounded vowel', 'uni': '\u0268'},
    'M': {'desc': 'close back unrounded vowel', 'uni': '\u026f'},
    'O': {'desc': 'open-mid back rounded vowel', 'uni': '\u0254'},
    'Q': {'desc': 'open back rounded vowel', 'uni': '\u0252'},
    'U': {'desc': 'near-close back rounded vowel', 'uni': '\u028a'},
    'U*': {'desc': 'near-close central rounded vowel', 'uni': '\u0289'},
    'V': {'desc': 'open-mid back unrounded vowel', 'uni': '\u028c'},
    'Y': {'desc': 'near-close front rounded vowel',  'uni': '\u028f'},
    '@': {'desc': 'schwa', 'uni': '\u0259'},
    '@*': {'desc': 'close mid-central unrounded vowel', 'uni': '\u0258'},
    '@`': {'desc': 'r-colored schwa', 'uni': '\u02de'},
    '{': {'desc': 'near-open front unrounded vowel', 'uni': '\u00e6'},
    '}': {'desc': 'close central rounded vowel', 'uni': '\u0289'},
    '2': {'desc': 'close-mid front rounded vowel', 'uni': '\u00f8'},
    '3': {'desc': 'open-mid central unrounded vowel', 'uni': '\u025c'},
    '3*': {'desc': 'open-mid central rounded vowel', 'uni': '\u025e'},
    '6': {'desc': 'near-open central vowel', 'uni': '\u0250'},
    '7': {'desc': 'close-mid back unrounded vowel', 'uni': '\u0264'},
    '8': {'desc': 'close-mid central rounded vowel', 'uni': '\u0275'},
    '9': {'desc': 'open -mid front rounded vowel', 'uni': '\u0153'},
    '&': {'desc': 'open front rounded vowel', 'uni': '\u0276'}
}
